#*****************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# pynq-z2-project.tcl: Tcl script for re-creating project 'pynq-z2'
#
# Generated by Vivado on Tue Aug 19 10:00:09 -0400 2025
# IP Build 6138677 on Thu May 22 03:10:11 MDT 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (pynq-z2-project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/users/keck/Desktop/zynqdp8/pynq-z2/pynq-z2.srcs/sources_1/bd/pynq_z2_block/pynq_z2_block.bd"
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/ram/axi_bram.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/socdp8_package.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/console/lamp.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/console/console_mux.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/df32.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/uart.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/pt08.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/pc04.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/tc08.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/rf08.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/kw8i.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/rk8.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/io/io_controller.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/inst_common_package.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/and.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/eae/asr.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/dca.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/eae/dvi.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/tad.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/isz.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/jms.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/jmp.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/iot.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/opr.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/eae/muy.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/eae/nmi.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/eae/shl.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/eae/lsr.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/instructions/instruction_multiplexer.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/interrupt_controller.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/memory_control.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/timing_manual.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/timing_auto.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/registers.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/cpu/pdp8.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/console/pidp8_console.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/rtl/console/xilinx_console_driver.vhd"
#    "C:/Users/keck/Desktop/zynqdp8/SoCDP8/src/fpga/boards/pynq-z2_constraints.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/pynq-z2/pynq-z2.srcs/sources_1/bd/pynq_z2_block/pynq_z2_block.bd"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/ram/axi_bram.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/socdp8_package.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/console/lamp.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/console/console_mux.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/df32.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/uart.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/pt08.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/pc04.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/tc08.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/rf08.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/kw8i.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/rk8.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/io/io_controller.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/inst_common_package.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/and.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/asr.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/dca.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/dvi.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/tad.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/isz.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/jms.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/jmp.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/iot.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/opr.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/muy.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/nmi.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/shl.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/lsr.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/instruction_multiplexer.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/interrupt_controller.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/memory_control.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/timing_manual.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/timing_auto.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/registers.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/cpu/pdp8.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/console/pidp8_console.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/rtl/console/xilinx_console_driver.vhd"]"\
 "[file normalize "$origin_dir/SoCDP8/src/fpga/boards/pynq-z2_constraints.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "pynq-z2"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "pynq-z2-project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/pynq-z2"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg400-1" -objects $obj
set_property -name "platform.board_id" -value "pynq-z2" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "71" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "68" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "71" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "71" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "71" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "68" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "71" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "624" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/ram/axi_bram.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/socdp8_package.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/console/lamp.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/console/console_mux.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/df32.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/uart.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/pt08.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/pc04.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/tc08.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/rf08.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/kw8i.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/rk8.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/io/io_controller.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/inst_common_package.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/and.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/eae/asr.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/dca.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/eae/dvi.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/tad.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/isz.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/jms.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/jmp.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/iot.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/opr.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/eae/muy.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/eae/nmi.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/eae/shl.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/eae/lsr.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/instructions/instruction_multiplexer.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/interrupt_controller.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/memory_control.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/timing_manual.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/timing_auto.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/registers.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/cpu/pdp8.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/console/pidp8_console.vhd"] \
 [file normalize "${origin_dir}/SoCDP8/src/fpga/rtl/console/xilinx_console_driver.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Add local files from the original project (-no_copy_sources specified)
# set files [list \
 # [file normalize "${origin_dir}/pynq-z2/pynq-z2.srcs/sources_1/bd/pynq_z2_block/pynq_z2_block.bd" ]\
# ]
# set added_files [add_files -fileset sources_1 $files]

#call make_wrapper to create wrapper files
# if { [get_property IS_LOCKED [ get_files -norecurse pynq_z2_block.bd] ] == 1  } {
  # import_files -fileset sources_1 [file normalize "${origin_dir}/pynq-z2/pynq-z2.gen/sources_1/bd/pynq_z2_block/hdl/pynq_z2_block_wrapper.vhd" ]
# } else {
  # set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse pynq_z2_block.bd] -top]
  # add_files -norecurse -fileset sources_1 $wrapper_path
# }


# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/SoCDP8/src/fpga/rtl/ram/axi_bram.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/socdp8_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/console/lamp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/console/console_mux.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/df32.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/uart.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/pt08.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/pc04.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/tc08.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/rf08.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/kw8i.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/rk8.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/io/io_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/inst_common_package.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/and.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/asr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/dca.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/dvi.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/tad.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/isz.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/jms.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/jmp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/iot.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/opr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/muy.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/nmi.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/shl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/eae/lsr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/instructions/instruction_multiplexer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/interrupt_controller.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/memory_control.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/timing_manual.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/timing_auto.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/registers.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/cpu/pdp8.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/console/pidp8_console.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj

set file "$origin_dir/SoCDP8/src/fpga/rtl/console/xilinx_console_driver.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# set file "pynq_z2_block/pynq_z2_block.bd"
# set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
# set_property -name "registered_with_manager" -value "1" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "pynq_z2_block_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/SoCDP8/src/fpga/boards/pynq-z2_constraints.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/SoCDP8/src/fpga/boards/pynq-z2_constraints.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7z020clg400-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "io_controller" -objects $obj
set_property -name "top_arch" -value "Behavioral" -objects $obj
set_property -name "top_file" -value "SoCDP8/src/fpga/rtl/io/io_controller.vhd" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg400-1 -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7z020clg400-1" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg400-1 -flow {Vivado Implementation 2025} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7z020clg400-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
